config/routes.rb
Shoppy::Application.routes.draw do

  root'items#index'

  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index

    @items = Item.all
    
  end

  def new
    @item = Item.new
  end

  def create
    Item.create(item_params)
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:thing, :amount)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<h1> Here's what we need this week! </h1>

 <% @items.each do |i| %>
 <hr> 
<p> <strong> Thing: <%= i.thing %> </strong> </p>
<p> <strong> Amount: <%= i.amount %> </strong> </p>

<%end%>
<%=link_to 'Add more stuff', new_item_path %>

app/views/items/new.html.erb
<div class="items">

<h1> What do we need to buy? </h1>

  <%= simple_form_for @item do |i| %>
  <%= i.input :thing %>
  <%= i.input :amount %>
  <br />
  <%= i.submit 'Add!', class:"btn btn-primary"%>
  <%end%>

  </div>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoppy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>